# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/f85/wliu05/Desktop/pong

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/f85/wliu05/Desktop/pong

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local

.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip

.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/f85/wliu05/Desktop/pong/CMakeFiles /home/f85/wliu05/Desktop/pong/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/f85/wliu05/Desktop/pong/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

#=============================================================================
# Target rules for targets named pong_core

# Build rule for target.
pong_core: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pong_core
.PHONY : pong_core

# fast build rule for target.
pong_core/fast:
	$(MAKE) -f CMakeFiles/pong_core.dir/build.make CMakeFiles/pong_core.dir/build
.PHONY : pong_core/fast

#=============================================================================
# Target rules for targets named Box2D

# Build rule for target.
Box2D: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Box2D
.PHONY : Box2D

# fast build rule for target.
Box2D/fast:
	$(MAKE) -f Box2D/Box2D/CMakeFiles/Box2D.dir/build.make Box2D/Box2D/CMakeFiles/Box2D.dir/build
.PHONY : Box2D/fast

bin/main.o: bin/main.cpp.o

.PHONY : bin/main.o

# target to build an object file
bin/main.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/bin/main.cpp.o
.PHONY : bin/main.cpp.o

bin/main.i: bin/main.cpp.i

.PHONY : bin/main.i

# target to preprocess a source file
bin/main.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/bin/main.cpp.i
.PHONY : bin/main.cpp.i

bin/main.s: bin/main.cpp.s

.PHONY : bin/main.s

# target to generate assembly for a file
bin/main.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/bin/main.cpp.s
.PHONY : bin/main.cpp.s

src/Entities/Bullets/BeamBullet.o: src/Entities/Bullets/BeamBullet.cpp.o

.PHONY : src/Entities/Bullets/BeamBullet.o

# target to build an object file
src/Entities/Bullets/BeamBullet.cpp.o:
	$(MAKE) -f CMakeFiles/pong_core.dir/build.make CMakeFiles/pong_core.dir/src/Entities/Bullets/BeamBullet.cpp.o
.PHONY : src/Entities/Bullets/BeamBullet.cpp.o

src/Entities/Bullets/BeamBullet.i: src/Entities/Bullets/BeamBullet.cpp.i

.PHONY : src/Entities/Bullets/BeamBullet.i

# target to preprocess a source file
src/Entities/Bullets/BeamBullet.cpp.i:
	$(MAKE) -f CMakeFiles/pong_core.dir/build.make CMakeFiles/pong_core.dir/src/Entities/Bullets/BeamBullet.cpp.i
.PHONY : src/Entities/Bullets/BeamBullet.cpp.i

src/Entities/Bullets/BeamBullet.s: src/Entities/Bullets/BeamBullet.cpp.s

.PHONY : src/Entities/Bullets/BeamBullet.s

# target to generate assembly for a file
src/Entities/Bullets/BeamBullet.cpp.s:
	$(MAKE) -f CMakeFiles/pong_core.dir/build.make CMakeFiles/pong_core.dir/src/Entities/Bullets/BeamBullet.cpp.s
.PHONY : src/Entities/Bullets/BeamBullet.cpp.s

src/Entities/Bullets/BoomerangBullet.o: src/Entities/Bullets/BoomerangBullet.cpp.o

.PHONY : src/Entities/Bullets/BoomerangBullet.o

# target to build an object file
src/Entities/Bullets/BoomerangBullet.cpp.o:
	$(MAKE) -f CMakeFiles/pong_core.dir/build.make CMakeFiles/pong_core.dir/src/Entities/Bullets/BoomerangBullet.cpp.o
.PHONY : src/Entities/Bullets/BoomerangBullet.cpp.o

src/Entities/Bullets/BoomerangBullet.i: src/Entities/Bullets/BoomerangBullet.cpp.i

.PHONY : src/Entities/Bullets/BoomerangBullet.i

# target to preprocess a source file
src/Entities/Bullets/BoomerangBullet.cpp.i:
	$(MAKE) -f CMakeFiles/pong_core.dir/build.make CMakeFiles/pong_core.dir/src/Entities/Bullets/BoomerangBullet.cpp.i
.PHONY : src/Entities/Bullets/BoomerangBullet.cpp.i

src/Entities/Bullets/BoomerangBullet.s: src/Entities/Bullets/BoomerangBullet.cpp.s

.PHONY : src/Entities/Bullets/BoomerangBullet.s

# target to generate assembly for a file
src/Entities/Bullets/BoomerangBullet.cpp.s:
	$(MAKE) -f CMakeFiles/pong_core.dir/build.make CMakeFiles/pong_core.dir/src/Entities/Bullets/BoomerangBullet.cpp.s
.PHONY : src/Entities/Bullets/BoomerangBullet.cpp.s

src/Entities/Bullets/GuidedBullet.o: src/Entities/Bullets/GuidedBullet.cpp.o

.PHONY : src/Entities/Bullets/GuidedBullet.o

# target to build an object file
src/Entities/Bullets/GuidedBullet.cpp.o:
	$(MAKE) -f CMakeFiles/pong_core.dir/build.make CMakeFiles/pong_core.dir/src/Entities/Bullets/GuidedBullet.cpp.o
.PHONY : src/Entities/Bullets/GuidedBullet.cpp.o

src/Entities/Bullets/GuidedBullet.i: src/Entities/Bullets/GuidedBullet.cpp.i

.PHONY : src/Entities/Bullets/GuidedBullet.i

# target to preprocess a source file
src/Entities/Bullets/GuidedBullet.cpp.i:
	$(MAKE) -f CMakeFiles/pong_core.dir/build.make CMakeFiles/pong_core.dir/src/Entities/Bullets/GuidedBullet.cpp.i
.PHONY : src/Entities/Bullets/GuidedBullet.cpp.i

src/Entities/Bullets/GuidedBullet.s: src/Entities/Bullets/GuidedBullet.cpp.s

.PHONY : src/Entities/Bullets/GuidedBullet.s

# target to generate assembly for a file
src/Entities/Bullets/GuidedBullet.cpp.s:
	$(MAKE) -f CMakeFiles/pong_core.dir/build.make CMakeFiles/pong_core.dir/src/Entities/Bullets/GuidedBullet.cpp.s
.PHONY : src/Entities/Bullets/GuidedBullet.cpp.s

src/Entities/Bullets/MachineGunBullet.o: src/Entities/Bullets/MachineGunBullet.cpp.o

.PHONY : src/Entities/Bullets/MachineGunBullet.o

# target to build an object file
src/Entities/Bullets/MachineGunBullet.cpp.o:
	$(MAKE) -f CMakeFiles/pong_core.dir/build.make CMakeFiles/pong_core.dir/src/Entities/Bullets/MachineGunBullet.cpp.o
.PHONY : src/Entities/Bullets/MachineGunBullet.cpp.o

src/Entities/Bullets/MachineGunBullet.i: src/Entities/Bullets/MachineGunBullet.cpp.i

.PHONY : src/Entities/Bullets/MachineGunBullet.i

# target to preprocess a source file
src/Entities/Bullets/MachineGunBullet.cpp.i:
	$(MAKE) -f CMakeFiles/pong_core.dir/build.make CMakeFiles/pong_core.dir/src/Entities/Bullets/MachineGunBullet.cpp.i
.PHONY : src/Entities/Bullets/MachineGunBullet.cpp.i

src/Entities/Bullets/MachineGunBullet.s: src/Entities/Bullets/MachineGunBullet.cpp.s

.PHONY : src/Entities/Bullets/MachineGunBullet.s

# target to generate assembly for a file
src/Entities/Bullets/MachineGunBullet.cpp.s:
	$(MAKE) -f CMakeFiles/pong_core.dir/build.make CMakeFiles/pong_core.dir/src/Entities/Bullets/MachineGunBullet.cpp.s
.PHONY : src/Entities/Bullets/MachineGunBullet.cpp.s

src/Entities/Ships/RocketShip.o: src/Entities/Ships/RocketShip.cpp.o

.PHONY : src/Entities/Ships/RocketShip.o

# target to build an object file
src/Entities/Ships/RocketShip.cpp.o:
	$(MAKE) -f CMakeFiles/pong_core.dir/build.make CMakeFiles/pong_core.dir/src/Entities/Ships/RocketShip.cpp.o
.PHONY : src/Entities/Ships/RocketShip.cpp.o

src/Entities/Ships/RocketShip.i: src/Entities/Ships/RocketShip.cpp.i

.PHONY : src/Entities/Ships/RocketShip.i

# target to preprocess a source file
src/Entities/Ships/RocketShip.cpp.i:
	$(MAKE) -f CMakeFiles/pong_core.dir/build.make CMakeFiles/pong_core.dir/src/Entities/Ships/RocketShip.cpp.i
.PHONY : src/Entities/Ships/RocketShip.cpp.i

src/Entities/Ships/RocketShip.s: src/Entities/Ships/RocketShip.cpp.s

.PHONY : src/Entities/Ships/RocketShip.s

# target to generate assembly for a file
src/Entities/Ships/RocketShip.cpp.s:
	$(MAKE) -f CMakeFiles/pong_core.dir/build.make CMakeFiles/pong_core.dir/src/Entities/Ships/RocketShip.cpp.s
.PHONY : src/Entities/Ships/RocketShip.cpp.s

src/Entities/Turrets/BoomerangTurret.o: src/Entities/Turrets/BoomerangTurret.cpp.o

.PHONY : src/Entities/Turrets/BoomerangTurret.o

# target to build an object file
src/Entities/Turrets/BoomerangTurret.cpp.o:
	$(MAKE) -f CMakeFiles/pong_core.dir/build.make CMakeFiles/pong_core.dir/src/Entities/Turrets/BoomerangTurret.cpp.o
.PHONY : src/Entities/Turrets/BoomerangTurret.cpp.o

src/Entities/Turrets/BoomerangTurret.i: src/Entities/Turrets/BoomerangTurret.cpp.i

.PHONY : src/Entities/Turrets/BoomerangTurret.i

# target to preprocess a source file
src/Entities/Turrets/BoomerangTurret.cpp.i:
	$(MAKE) -f CMakeFiles/pong_core.dir/build.make CMakeFiles/pong_core.dir/src/Entities/Turrets/BoomerangTurret.cpp.i
.PHONY : src/Entities/Turrets/BoomerangTurret.cpp.i

src/Entities/Turrets/BoomerangTurret.s: src/Entities/Turrets/BoomerangTurret.cpp.s

.PHONY : src/Entities/Turrets/BoomerangTurret.s

# target to generate assembly for a file
src/Entities/Turrets/BoomerangTurret.cpp.s:
	$(MAKE) -f CMakeFiles/pong_core.dir/build.make CMakeFiles/pong_core.dir/src/Entities/Turrets/BoomerangTurret.cpp.s
.PHONY : src/Entities/Turrets/BoomerangTurret.cpp.s

src/Entities/Turrets/GlueGunTurret.o: src/Entities/Turrets/GlueGunTurret.cpp.o

.PHONY : src/Entities/Turrets/GlueGunTurret.o

# target to build an object file
src/Entities/Turrets/GlueGunTurret.cpp.o:
	$(MAKE) -f CMakeFiles/pong_core.dir/build.make CMakeFiles/pong_core.dir/src/Entities/Turrets/GlueGunTurret.cpp.o
.PHONY : src/Entities/Turrets/GlueGunTurret.cpp.o

src/Entities/Turrets/GlueGunTurret.i: src/Entities/Turrets/GlueGunTurret.cpp.i

.PHONY : src/Entities/Turrets/GlueGunTurret.i

# target to preprocess a source file
src/Entities/Turrets/GlueGunTurret.cpp.i:
	$(MAKE) -f CMakeFiles/pong_core.dir/build.make CMakeFiles/pong_core.dir/src/Entities/Turrets/GlueGunTurret.cpp.i
.PHONY : src/Entities/Turrets/GlueGunTurret.cpp.i

src/Entities/Turrets/GlueGunTurret.s: src/Entities/Turrets/GlueGunTurret.cpp.s

.PHONY : src/Entities/Turrets/GlueGunTurret.s

# target to generate assembly for a file
src/Entities/Turrets/GlueGunTurret.cpp.s:
	$(MAKE) -f CMakeFiles/pong_core.dir/build.make CMakeFiles/pong_core.dir/src/Entities/Turrets/GlueGunTurret.cpp.s
.PHONY : src/Entities/Turrets/GlueGunTurret.cpp.s

src/Entities/Turrets/GuidedTurret.o: src/Entities/Turrets/GuidedTurret.cpp.o

.PHONY : src/Entities/Turrets/GuidedTurret.o

# target to build an object file
src/Entities/Turrets/GuidedTurret.cpp.o:
	$(MAKE) -f CMakeFiles/pong_core.dir/build.make CMakeFiles/pong_core.dir/src/Entities/Turrets/GuidedTurret.cpp.o
.PHONY : src/Entities/Turrets/GuidedTurret.cpp.o

src/Entities/Turrets/GuidedTurret.i: src/Entities/Turrets/GuidedTurret.cpp.i

.PHONY : src/Entities/Turrets/GuidedTurret.i

# target to preprocess a source file
src/Entities/Turrets/GuidedTurret.cpp.i:
	$(MAKE) -f CMakeFiles/pong_core.dir/build.make CMakeFiles/pong_core.dir/src/Entities/Turrets/GuidedTurret.cpp.i
.PHONY : src/Entities/Turrets/GuidedTurret.cpp.i

src/Entities/Turrets/GuidedTurret.s: src/Entities/Turrets/GuidedTurret.cpp.s

.PHONY : src/Entities/Turrets/GuidedTurret.s

# target to generate assembly for a file
src/Entities/Turrets/GuidedTurret.cpp.s:
	$(MAKE) -f CMakeFiles/pong_core.dir/build.make CMakeFiles/pong_core.dir/src/Entities/Turrets/GuidedTurret.cpp.s
.PHONY : src/Entities/Turrets/GuidedTurret.cpp.s

src/Entities/Turrets/MachineGunTurret.o: src/Entities/Turrets/MachineGunTurret.cpp.o

.PHONY : src/Entities/Turrets/MachineGunTurret.o

# target to build an object file
src/Entities/Turrets/MachineGunTurret.cpp.o:
	$(MAKE) -f CMakeFiles/pong_core.dir/build.make CMakeFiles/pong_core.dir/src/Entities/Turrets/MachineGunTurret.cpp.o
.PHONY : src/Entities/Turrets/MachineGunTurret.cpp.o

src/Entities/Turrets/MachineGunTurret.i: src/Entities/Turrets/MachineGunTurret.cpp.i

.PHONY : src/Entities/Turrets/MachineGunTurret.i

# target to preprocess a source file
src/Entities/Turrets/MachineGunTurret.cpp.i:
	$(MAKE) -f CMakeFiles/pong_core.dir/build.make CMakeFiles/pong_core.dir/src/Entities/Turrets/MachineGunTurret.cpp.i
.PHONY : src/Entities/Turrets/MachineGunTurret.cpp.i

src/Entities/Turrets/MachineGunTurret.s: src/Entities/Turrets/MachineGunTurret.cpp.s

.PHONY : src/Entities/Turrets/MachineGunTurret.s

# target to generate assembly for a file
src/Entities/Turrets/MachineGunTurret.cpp.s:
	$(MAKE) -f CMakeFiles/pong_core.dir/build.make CMakeFiles/pong_core.dir/src/Entities/Turrets/MachineGunTurret.cpp.s
.PHONY : src/Entities/Turrets/MachineGunTurret.cpp.s

src/Entities/Turrets/RailGunTurret.o: src/Entities/Turrets/RailGunTurret.cpp.o

.PHONY : src/Entities/Turrets/RailGunTurret.o

# target to build an object file
src/Entities/Turrets/RailGunTurret.cpp.o:
	$(MAKE) -f CMakeFiles/pong_core.dir/build.make CMakeFiles/pong_core.dir/src/Entities/Turrets/RailGunTurret.cpp.o
.PHONY : src/Entities/Turrets/RailGunTurret.cpp.o

src/Entities/Turrets/RailGunTurret.i: src/Entities/Turrets/RailGunTurret.cpp.i

.PHONY : src/Entities/Turrets/RailGunTurret.i

# target to preprocess a source file
src/Entities/Turrets/RailGunTurret.cpp.i:
	$(MAKE) -f CMakeFiles/pong_core.dir/build.make CMakeFiles/pong_core.dir/src/Entities/Turrets/RailGunTurret.cpp.i
.PHONY : src/Entities/Turrets/RailGunTurret.cpp.i

src/Entities/Turrets/RailGunTurret.s: src/Entities/Turrets/RailGunTurret.cpp.s

.PHONY : src/Entities/Turrets/RailGunTurret.s

# target to generate assembly for a file
src/Entities/Turrets/RailGunTurret.cpp.s:
	$(MAKE) -f CMakeFiles/pong_core.dir/build.make CMakeFiles/pong_core.dir/src/Entities/Turrets/RailGunTurret.cpp.s
.PHONY : src/Entities/Turrets/RailGunTurret.cpp.s

src/Entities/Turrets/RicochetTurret.o: src/Entities/Turrets/RicochetTurret.cpp.o

.PHONY : src/Entities/Turrets/RicochetTurret.o

# target to build an object file
src/Entities/Turrets/RicochetTurret.cpp.o:
	$(MAKE) -f CMakeFiles/pong_core.dir/build.make CMakeFiles/pong_core.dir/src/Entities/Turrets/RicochetTurret.cpp.o
.PHONY : src/Entities/Turrets/RicochetTurret.cpp.o

src/Entities/Turrets/RicochetTurret.i: src/Entities/Turrets/RicochetTurret.cpp.i

.PHONY : src/Entities/Turrets/RicochetTurret.i

# target to preprocess a source file
src/Entities/Turrets/RicochetTurret.cpp.i:
	$(MAKE) -f CMakeFiles/pong_core.dir/build.make CMakeFiles/pong_core.dir/src/Entities/Turrets/RicochetTurret.cpp.i
.PHONY : src/Entities/Turrets/RicochetTurret.cpp.i

src/Entities/Turrets/RicochetTurret.s: src/Entities/Turrets/RicochetTurret.cpp.s

.PHONY : src/Entities/Turrets/RicochetTurret.s

# target to generate assembly for a file
src/Entities/Turrets/RicochetTurret.cpp.s:
	$(MAKE) -f CMakeFiles/pong_core.dir/build.make CMakeFiles/pong_core.dir/src/Entities/Turrets/RicochetTurret.cpp.s
.PHONY : src/Entities/Turrets/RicochetTurret.cpp.s

src/States/FinishState.o: src/States/FinishState.cpp.o

.PHONY : src/States/FinishState.o

# target to build an object file
src/States/FinishState.cpp.o:
	$(MAKE) -f CMakeFiles/pong_core.dir/build.make CMakeFiles/pong_core.dir/src/States/FinishState.cpp.o
.PHONY : src/States/FinishState.cpp.o

src/States/FinishState.i: src/States/FinishState.cpp.i

.PHONY : src/States/FinishState.i

# target to preprocess a source file
src/States/FinishState.cpp.i:
	$(MAKE) -f CMakeFiles/pong_core.dir/build.make CMakeFiles/pong_core.dir/src/States/FinishState.cpp.i
.PHONY : src/States/FinishState.cpp.i

src/States/FinishState.s: src/States/FinishState.cpp.s

.PHONY : src/States/FinishState.s

# target to generate assembly for a file
src/States/FinishState.cpp.s:
	$(MAKE) -f CMakeFiles/pong_core.dir/build.make CMakeFiles/pong_core.dir/src/States/FinishState.cpp.s
.PHONY : src/States/FinishState.cpp.s

src/States/GameStateManager.o: src/States/GameStateManager.cpp.o

.PHONY : src/States/GameStateManager.o

# target to build an object file
src/States/GameStateManager.cpp.o:
	$(MAKE) -f CMakeFiles/pong_core.dir/build.make CMakeFiles/pong_core.dir/src/States/GameStateManager.cpp.o
.PHONY : src/States/GameStateManager.cpp.o

src/States/GameStateManager.i: src/States/GameStateManager.cpp.i

.PHONY : src/States/GameStateManager.i

# target to preprocess a source file
src/States/GameStateManager.cpp.i:
	$(MAKE) -f CMakeFiles/pong_core.dir/build.make CMakeFiles/pong_core.dir/src/States/GameStateManager.cpp.i
.PHONY : src/States/GameStateManager.cpp.i

src/States/GameStateManager.s: src/States/GameStateManager.cpp.s

.PHONY : src/States/GameStateManager.s

# target to generate assembly for a file
src/States/GameStateManager.cpp.s:
	$(MAKE) -f CMakeFiles/pong_core.dir/build.make CMakeFiles/pong_core.dir/src/States/GameStateManager.cpp.s
.PHONY : src/States/GameStateManager.cpp.s

src/States/MenuState.o: src/States/MenuState.cpp.o

.PHONY : src/States/MenuState.o

# target to build an object file
src/States/MenuState.cpp.o:
	$(MAKE) -f CMakeFiles/pong_core.dir/build.make CMakeFiles/pong_core.dir/src/States/MenuState.cpp.o
.PHONY : src/States/MenuState.cpp.o

src/States/MenuState.i: src/States/MenuState.cpp.i

.PHONY : src/States/MenuState.i

# target to preprocess a source file
src/States/MenuState.cpp.i:
	$(MAKE) -f CMakeFiles/pong_core.dir/build.make CMakeFiles/pong_core.dir/src/States/MenuState.cpp.i
.PHONY : src/States/MenuState.cpp.i

src/States/MenuState.s: src/States/MenuState.cpp.s

.PHONY : src/States/MenuState.s

# target to generate assembly for a file
src/States/MenuState.cpp.s:
	$(MAKE) -f CMakeFiles/pong_core.dir/build.make CMakeFiles/pong_core.dir/src/States/MenuState.cpp.s
.PHONY : src/States/MenuState.cpp.s

src/States/PlayState.o: src/States/PlayState.cpp.o

.PHONY : src/States/PlayState.o

# target to build an object file
src/States/PlayState.cpp.o:
	$(MAKE) -f CMakeFiles/pong_core.dir/build.make CMakeFiles/pong_core.dir/src/States/PlayState.cpp.o
.PHONY : src/States/PlayState.cpp.o

src/States/PlayState.i: src/States/PlayState.cpp.i

.PHONY : src/States/PlayState.i

# target to preprocess a source file
src/States/PlayState.cpp.i:
	$(MAKE) -f CMakeFiles/pong_core.dir/build.make CMakeFiles/pong_core.dir/src/States/PlayState.cpp.i
.PHONY : src/States/PlayState.cpp.i

src/States/PlayState.s: src/States/PlayState.cpp.s

.PHONY : src/States/PlayState.s

# target to generate assembly for a file
src/States/PlayState.cpp.s:
	$(MAKE) -f CMakeFiles/pong_core.dir/build.make CMakeFiles/pong_core.dir/src/States/PlayState.cpp.s
.PHONY : src/States/PlayState.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... list_install_components"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... main"
	@echo "... pong_core"
	@echo "... Box2D"
	@echo "... bin/main.o"
	@echo "... bin/main.i"
	@echo "... bin/main.s"
	@echo "... src/Entities/Bullets/BeamBullet.o"
	@echo "... src/Entities/Bullets/BeamBullet.i"
	@echo "... src/Entities/Bullets/BeamBullet.s"
	@echo "... src/Entities/Bullets/BoomerangBullet.o"
	@echo "... src/Entities/Bullets/BoomerangBullet.i"
	@echo "... src/Entities/Bullets/BoomerangBullet.s"
	@echo "... src/Entities/Bullets/GuidedBullet.o"
	@echo "... src/Entities/Bullets/GuidedBullet.i"
	@echo "... src/Entities/Bullets/GuidedBullet.s"
	@echo "... src/Entities/Bullets/MachineGunBullet.o"
	@echo "... src/Entities/Bullets/MachineGunBullet.i"
	@echo "... src/Entities/Bullets/MachineGunBullet.s"
	@echo "... src/Entities/Ships/RocketShip.o"
	@echo "... src/Entities/Ships/RocketShip.i"
	@echo "... src/Entities/Ships/RocketShip.s"
	@echo "... src/Entities/Turrets/BoomerangTurret.o"
	@echo "... src/Entities/Turrets/BoomerangTurret.i"
	@echo "... src/Entities/Turrets/BoomerangTurret.s"
	@echo "... src/Entities/Turrets/GlueGunTurret.o"
	@echo "... src/Entities/Turrets/GlueGunTurret.i"
	@echo "... src/Entities/Turrets/GlueGunTurret.s"
	@echo "... src/Entities/Turrets/GuidedTurret.o"
	@echo "... src/Entities/Turrets/GuidedTurret.i"
	@echo "... src/Entities/Turrets/GuidedTurret.s"
	@echo "... src/Entities/Turrets/MachineGunTurret.o"
	@echo "... src/Entities/Turrets/MachineGunTurret.i"
	@echo "... src/Entities/Turrets/MachineGunTurret.s"
	@echo "... src/Entities/Turrets/RailGunTurret.o"
	@echo "... src/Entities/Turrets/RailGunTurret.i"
	@echo "... src/Entities/Turrets/RailGunTurret.s"
	@echo "... src/Entities/Turrets/RicochetTurret.o"
	@echo "... src/Entities/Turrets/RicochetTurret.i"
	@echo "... src/Entities/Turrets/RicochetTurret.s"
	@echo "... src/States/FinishState.o"
	@echo "... src/States/FinishState.i"
	@echo "... src/States/FinishState.s"
	@echo "... src/States/GameStateManager.o"
	@echo "... src/States/GameStateManager.i"
	@echo "... src/States/GameStateManager.s"
	@echo "... src/States/MenuState.o"
	@echo "... src/States/MenuState.i"
	@echo "... src/States/MenuState.s"
	@echo "... src/States/PlayState.o"
	@echo "... src/States/PlayState.i"
	@echo "... src/States/PlayState.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

